# Configure all parameters equal for all instances elastic search, changes in "docker-compose" tag "environment"
network.host: "0.0.0.0"
network.publish_host: "0.0.0.0"

# this value is required because we set "network.host"
# be sure to modify it appropriately for a production cluster deployment
# deprecate option in future versions
#discovery.zen.minimum_master_nodes: 1

node.master: true
node.ingest: false
node.data: true


bootstrap.memory_lock: true

http.host: 0.0.0.0 # accept request from remote
http.cors.enabled: true
http.cors.allow-origin: "*"

#xpack.monitoring.enabled: true
#xpack.monitoring.collection.enabled: true
#xpack.monitoring.collection.interval: 300s

#xpack.security.enabled: true

#xpack.security.transport.ssl.enabled: true
#xpack.security.transport.ssl.verification_mode: certificate
#xpack.security.transport.ssl.keystore.path: /usr/share/elasticsearch/config/elastic-stack-certificates.p12
#xpack.security.transport.ssl.truststore.path: /usr/share/elasticsearch/config/elastic-stack-certificates.p12

#xpack.security.http.ssl.client_authentication: optional
