# Generated by Django 3.0.8 on 2020-07-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload_storage')),
            ],
        ),
    ]
